config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#home'

  resources :users do
    collection do
      get 'login' => 'users#login'
      post 'login' => 'users#sign_in'
      post 'logout' => 'users#logout'
    end
  end

  resources :comments
  resources :posts do
    collection do
      get 'search_results' => 'posts#search_results'
      get 'search_results_destination' => 'posts#search_destination_date'
    end
  end
  resources :transactions
  resources :categories
  resources :bids

  get 'searches/search_username' => 'searches#search_username'
  get 'searches/search_flight_number'=> 'searches#search_flight_number'
  get 'searches/search_destination_date'=> 'searches#search_destination_date'
  get '/my_posts' => 'posts#person_posts'
  get '/my_bids' => 'bids#person_bids'

end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password

	validates_presence_of :username
	validates_uniqueness_of :username, :case_sensitive=>false
	validates_presence_of :password
	validates_confirmation_of :password	

	def self.authenticate(username, password)
		user = find_by_username(username)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end	

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])

		if @user
			@person = Person.find_by(user_id: @user.id)
			@posts = Post.where(poster_id: @user.id)
			@comments = Comment.where(user_id: @user.id)
		else
			redirect_to :root
		end
	end

	def new
		
	end

	def create
		@user = User.new(user_params)

		if @user.save
			@person = Person.new(person_params)
			if @person.save
				flash[:notice] = "Successfully Created Account!"
				redirect_to login_users_path
			else
				flash.now[:error] = @person.errors.full_messages.first
				render 'users/new'
			end
		else
			flash.now[:error] = @user.errors.full_messages.first
			render 'users/new'
		end
	end

	def edit
			
	end

	def update
			
	end
 
  def destroy
    
    @User = User.find(current_user.id)

    @posts = Post.where(user_id: current_user.id)

    @posts.each do |x|
      x.destroy
    end

  end
  def login
    
    if current_user == nil
      @user = User.new
    end

  end

  def sign_in
    
    username = params[:user][:username]
    password = params[:user][:password]

    user = User.authenticate(username, password)

    if user
      session[:user_id] = user.id
      @user = (current_user.role == 'admin')? User.find(current_user.id) : nil
      redirect_to :root
    else
      flash[:error] = "Invalid username or password."
      redirect_to login_users_path
    end
  end

	def logout
		session[:user_id] = nil
		redirect_to :root		
	end

	private
		def user_params
			params.require(:user).permit(:username, :password, :password_confirmation, :role)
		end

		def person_params
			params.require(:person).permit(:first_name, :last_name, :mid_name, :address, :contact_num, :email).merge(:user_id => @user.id)
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_tag :role=>'form', :action=>'create' do %>

	<div class="row">
	<!-- <div class="col-md-4"></div> -->
  <div class="col-md-4"><br>  
	<%#= label :user, 'Username: ' %>

	<h4>Account Information</h4>
	<%= text_field :user, :username, :value=>@username, :placeholder=>"Username", class: "form-control" %>
	<!-- </div> -->
	<br>

  <!-- <div class="col-md-8"><br>   -->
	<%#= label :user, 'Password: ' %>
	<%= password_field :user, :password, :placeholder=>'Password', class: "form-control"%>
	<!-- </div> -->
	<br>

	<!-- <div class="col-md-8"><br>   -->
	<%#= label :user, 'Confirm Password: ' %>
	<%= password_field :user, :password_confirmation, :placeholder=>'Confirm password', class: "form-control"%>
	<!-- </div> -->
	<br>

	<%= hidden_field :user, :role, :value=>'regular' %>

	<!-- <div class="col-md-8"><br>   -->
	<%#= label :person, 'First Name: ' %>
	<!-- <div class="form-inline"> -->
	<h4>Personal Details</h4>
	<%= text_field :person, :first_name, :placeholder=>'First name',class: "form-control" %>
	<br>
	<%= text_field :person, :mid_name, :placeholder=>'Middle name',class: "form-control" %>
	<br>
	<%= text_field :person, :last_name, :placeholder=>'Last name',class: "form-control" %>
	<!-- </div> -->
	<br>
	
	<%= text_field :person, :address, :placeholder=>'Address',class: "form-control" %>
	<br>

	<%= text_field :person, :contact_num, :placeholder=>'Contact number',class: "form-control" %>
	<br>
	
	<%= text_field :person, :email, :placeholder=>'Email',class: "form-control" %>
	<br>

	<div class="pull-right"><br> 
	<%= button_tag 'Create Account', :type=>'submit', :class=>'btn btn-primary'%>
	</div>
	</div>
<% end %>

app/views/users/login.html.erb
<div class="col-md-4"></div>
<div class="col-md-4 login">
<center>
<img src="<%= asset_path 'Logo1.png'%>"/>
<h2>Sign in</h2>
</center>

<%= render 'layouts/flash' %>
<% if current_user %>
		Currently logged in as <strong><%= current_user.username %></strong>.
		Please logout before logging in as a different user.
<% else %>
	<%= form_for @user, :role=>'form', :as=>:user, :url=>login_users_path(@user) do |f| %>

			<div class="form-group">
		    <div class="input-group">
		      <%= f.text_field :username,class: "form-control", placeholder: "Username" %>
		      <span class="input-group-addon"><span class="glyphicon glyphicon-user"></span></span>
		    </div>
		  </div>

			<div class="form-group">
		    <div class="input-group">
		      <%= f.password_field :password, autocomplete: "off", class: "form-control", placeholder: "Password" %>
		      <span class="input-group-addon"><span class="glyphicon glyphicon-lock"></span></span>
		    </div>
		  </div>

			<div class="form-group">
		    <%= f.submit "Login", class: "btn btn-block btn-primary" %>
		  </div>
	<% end %>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Register</h1>
<%= render 'layouts/flash' %>
<%= render 'users/form' %>

app/views/users/show.html.erb
<h2 class='profile-name'>
	<span><img class="profile-pic" src="<%= asset_path 'default_profile.jpg'%>"></span>
	<%= @person.fullname %>
</h2>

Address: <%= @person.address %><br>
Contact Number: <%= @person.contact_num %><br>
E-mail Address: <%= @person.email %><br>

<br>

<h2> Posts: </h2>

<table class='table'>
<% if @posts.length > 0 %>
	<% @posts.reverse.each do |x| %>

		<tr><td>
		<h4><%= x.origin %> to <%= x.destination %></h4>
		<small>
			Category: <%= x.category %> | 
			posted by  
			<% if User.find(x.poster_id).username == current_user.username %>
				you
			<% else %>
				<%= User.find(x.poster_id).username%>
			<% end %>
			on <%= x.created_at.to_time.strftime("%b %d, %Y, %I:%M %P") %><br>
		</small>
		Date of Flight: <%= x.date_of_flight.to_time.strftime("%b %d, %Y, %I:%M %P")%><br>
		<% if x.category == 'request' %>
			Weight Needed: 		
		<% else %>
			Weight Offered: 
		<% end %>
		
		<%= x.weight %> kgs<br><br>
		<%= link_to post_path(x), class: 'btn btn-primary btn-xs' do %> 
		View <span class="badge"><%= Bid.where(post_id: x.id).count %></span>
		<% end %>
		<% if current_user == User.find(x.poster_id) %> 
			<%= link_to 'Edit', edit_post_path(id: x.id), class: 'btn btn-primary btn-xs btn-warning' %> 
			<%= link_to 'Delete' ,post_path(user_id: x.poster_id, id: x.id), method: :delete, class: 'btn btn-primary btn-xs btn-danger' %>
		<% end %>

	</td></tr>
	<% end %>
<% else %>
	This user doesn't have any posts yet.
<% end %>
</table>

<h2> Comments: </h2>

<div class=' col-md-8'>

<% if @comments.length != 0 %>
<ul class="timeline" style="margin-left: -600px;">
	<% @comments.each do |x| %>
		<li class="timeline-inverted" >
			<div class="timeline-badge">
    		<i class="glyphicon glyphicon-user"></i>
    	</div>
      <div class="timeline-panel">
        <div class="timeline-heading">
          <h4 class="timeline-title"><%= User.find(x.commenter_id).username %></h4>
          <p><small class="text-muted"><%= x.created_at.to_time.strftime("%b %d, %Y, %I:%M %P") %></small>
						<% if x.commenter_id == current_user.id %>
						 | <%= link_to 'Edit', edit_comment_path(id: x.id) %>
						 | <%= link_to 'Delete', comment_path(user_id: @user.id, id: x.id), method: :delete%><br>
						<% end %>
						</small></p>
          <div class="timeline-body">
          	<%= x.comment %>
        	</div>
      </div>
    </div>
  </li>
	<% end %>
	</ul>
</div>
<div class="col-xs-12">	
<% else %>
	There are no comments available for this user.
<% end %>	

<br>
<br>
<% if current_user.id !=  @user.id %>
	<% @comment = Comment.new %>
	<%= render 'comments/form' %>
	<%#= link_to 'Add Comment', new_comment_path(user_id: @user.id) %>
<% end %>
</div>