config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#home'

  resources :users do
    collection do
      get 'login' => 'users#login'
      post 'login' => 'users#sign_in'
      post 'logout' => 'users#logout'
    end
  end

  resources :comments
  resources :posts do
    collection do
      get 'search_results' => 'posts#search_results'
      get 'search_results_destination' => 'posts#search_destination_date'
    end
  end
  resources :transactions
  resources :categories
  resources :bids

  get 'searches/search_username' => 'searches#search_username'
  get 'searches/search_flight_number'=> 'searches#search_flight_number'
  get 'searches/search_destination_date'=> 'searches#search_destination_date'
  get '/my_posts' => 'posts#person_posts'
  get '/my_bids' => 'bids#person_bids'

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @post = Post.new 
  end
  
  def index
    @posts = Post.all
  end

  def edit
    @post= Post.find(params[:id])
    dof = @post.date_of_flight.to_s.split('-')
    @dof_str = dof[1] + "/" + dof[2] + "/" + dof[0]
  end

  def update
    @post =  Post.find(params[:id])

    if @post.update(post_update_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.poster_id)
  end

  def create
    @post = Post.new(post_params)
   # @post.poster_id = current_user.id
    @post.date_of_flight = DateTime.strptime(params[:date], '%m/%d/%Y %I:%M %P')
    @post.is_active = true
    if @post.save 
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id]).destroy
    redirect_to @user
  end

  def search_results
    @flight_number = params[:flight_number]
    @posts = Post.where(flight_number: @flight_number)
  end

  def search_destination_date
    @destination = params[:destination]
    @origin = params[:origin]
    @date = params[:date]
    @posts = Post.where(id: -1)
    post_h = Post.all
    test = 0
    
    if @origin.length > 0 then
      post_h = post_h.where(origin: @origin)
      test += 1
    end

    if @destination.length > 0 then
      post_h = post_h.where(destination: @destination)
      test += 1
    end

    @date_arr = @date.to_s.split('/')

    if @date_arr.length > 0 then
        test += 1
        post_h = post_h.where('extract(year from date_of_flight) = ?', @date_arr[2])
        post_h = post_h.where('extract(month from date_of_flight) = ?', @date_arr[0])
        post_h = post_h.where('extract(day from date_of_flight) = ?', @date_arr[1])
    end

    if test > 0 then
      @posts = post_h
    end
  end
  
  
  private
    def post_params
      params.require(:post).permit(:poster_id, :weight, :date_of_flight, :details, :category, :flight_number, :is_active, :origin, :destination )

    end

    def post_update_params
      params.require(:post).permit(:poster_id, :weight, :date_of_flight, :details, :category, :flight_number, :is_active, :origin, :destination )
    end
    
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <div class="row">
  <!-- <div class="col-md-4"></div> -->
  <div class="col-md-8"><br>  
  
  <%= f.hidden_field :poster_id, :value => current_user.id %>

  <p>
    <%= f.label 'Weight (in kgs): ' %>
    <%= f.number_field :weight, class: "form-control" %>
    </p>
 <p>
    <%= f.label 'Origin: '%>
    <%= f.text_field :origin, class: "form-control" %>
 </p>
 <p>
    <%= f.label 'Desitination: '%>
    <%= f.text_field :destination, class: "form-control" %>
  </p>
 
  <p>
    <%= f.label 'Flight Number: '%>
    <%= f.text_field :flight_number, class: "form-control" %>
  </p>

  <p>
    <%= f.label 'Date of Flight: ' %>
    <% if @post.date_of_flight %>
    <%= text_field_tag :date, @post.date_of_flight.to_time.strftime("%b/%d/%Y %I:%M %p"), class: 'form-control', id:'datetimepicker4' %>
    <% else %>
    <%= text_field_tag :date, @post.date_of_flight, class: 'form-control', id:'datetimepicker4' %>
    <% end %>
  </p>

  <p>
    <%= f.label 'Details: ' %><br>
    <%= f.text_area(:details, size: "50x5", class: "form-control")%>
  </p>

   <p>

   <%= f.label 'Category: ' %>
   <%= f.select(:category, [['Request','request'],['Advertisement','advertisement']], {class: 'form-control'})  %>  
   </p>
  
  

  <%= f.hidden_field :is_active, value: true %>
 
 <div class="pull-right"><br> 
  <%= button_tag 'Submit', :type=>'submit', :class=>'btn btn-primary'%>
  </div>
 
 </div></div>
<% end %>

<script type="text/javascript">
      $(function () {
          $('#datetimepicker4').datetimepicker();
      });
</script>

app/views/posts/edit.html.erb
<%= render 'posts/form' %>

app/views/posts/index.html.erb
<table class="table">

<% @posts.each do |p| %>
  
  <% dof = p.date_of_flight.to_s.split("-") %>
  <% dof_str = dof[1] + "/" + dof[2] + "/" + dof[0] %>
  <tr><td>
  <div>
  <div>
		<span><img class="profile-pic-sm" src="<%= asset_path 'default_profile.jpg'%>"></span>
		<strong><%= Person.find(p.poster_id).fullname %></strong>
	</div>
	<div class='post-preview'>
    <!-- <strong>Poster</strong> <%#= Person.find(p.poster_id).fullname %> <br> -->
    Weight: <%= p.weight %> kgs<br>
    Date of Flight: <%= dof_str  %> <br>
    <%= link_to 'View details', p %> 
  </div>
  </div>
  </td></tr>
<% end %>

</table>

app/views/posts/new.html.erb
<h3>Share Your Luggage</h3>


<%= render 'posts/form' %>

app/views/posts/person_posts.html.erb
<% @posts = Post.where(poster_id: current_user.id) %>

<% @posts.each do |p| %>

<div class='post-content'>
  <div>
  <table class="table">
  	<tr><td>
  		<strong> Weight: </strong> <%= p.weight %> kgs <br>
  		<strong> Origin: </strong> <%= p.origin %> <br>
  		<strong> Destination: </strong> <%= p.destination %>  <br>
  		<strong> Flight Schedule: </strong> <%= p.date_of_flight.strftime("%b %d, %Y, %I:%M %P") %> <br>
  		<strong> Flight Number: </strong> <%= p.flight_number %>
  	</td></tr>
  	<tr>
  		<td>
  			 <strong> Details: </strong>
  				<p><%= p.details %></p>
  		</td>
  	</tr>
  </table>
<%= link_to 'View Post', p %>
</div>
<% end %>

app/views/posts/search_destination_date.html.erb
<h1>Search Results</h1>

<% if @posts.length > 0 %>
	<ul class="timeline">
	<% @posts.each do |x| %>

	    <% if x.category == 'advertisement' %>
	    	<li>
	    	<div class="timeline-badge">
	    	<i class="glyphicon glyphicon-tag"></i>
	    <% else %>
	    	<li class="timeline-inverted" >
		    <div class="timeline-badge warning">
	    	<i class="glyphicon glyphicon-flag"></i>
	    <% end %>
	    </div>
	      <div class="timeline-panel">
	        <div class="timeline-heading">
	          <h4 class="timeline-title">
	          	<%= link_to "From #{x.origin} to #{x.destination}", x %></h4>
	          <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> posted on <%= x.created_at.to_time.strftime("%b %d, %Y, %I:%M %P") %> | Category: <%= x.category %></small></p>
	          <div class="timeline-body">
	          	Posted by: <%= User.find(x.poster_id).username %><br>
							Date of Flight: <%= x.date_of_flight.to_time.strftime("%b %d, %Y, %I:%M %P")%><br>
							<% if x.category == 'request' %>
								Weight Needed: 		
							<% else %>
								Weight Offered: 
							<% end %>
							<%= x.weight %> kgs<br>
						</div>
					</div>
				</div>
			</li>
	<% end %> 
<% else %>
	No flight matches
<% end %>

app/views/posts/search_results.html.erb
<h1>Search Results</h1>




<% if @posts.length > 0 %>
	<ul class="timeline">
	<% i = 0 %>
	<% @posts.each do |x| %>
		<% if x.category == 'advertisement' %>
	    	<li>
	    	<div class="timeline-badge">
	    	<i class="glyphicon glyphicon-tag"></i>
	    <% else %>
	    	<li class="timeline-inverted" >
		    <div class="timeline-badge warning">
	    	<i class="glyphicon glyphicon-flag"></i>
	    <% end %>
	    </div>
	      <div class="timeline-panel">
	        <div class="timeline-heading">
	          <h4 class="timeline-title">
	          	<%= link_to "From #{x.origin} to #{x.destination}", x %></h4>
	          <p><small class="text-muted"><i class="glyphicon glyphicon-time"></i> posted on <%= x.created_at.to_time.strftime("%b %d, %Y, %I:%M %P") %> | Category: <%= x.category %></small></p>
	          <div class="timeline-body">
	          	Posted by: <%= User.find(x.poster_id).username %><br>
							Date of Flight: <%= x.date_of_flight.to_time.strftime("%b %d, %Y, %I:%M %P")%><br>
							<% if x.category == 'request' %>
								Weight Needed: 		
							<% else %>
								Weight Offered: 
							<% end %>
							<%= x.weight %> kgs<br>
						</div>
					</div>
				</div>
			</li>
			<% i+=1 %>
	<% end %> 
<% else %>
	No flight matches with flight number: <%= @flight_number %>
<% end %>

app/views/posts/show.html.erb
<div class="post-ad">
  <div class="pull-left" style="padding-top:20px; margin-right: 20px;">
  <span><img class="profile-pic" src="<%= asset_path 'default_profile.jpg'%>"></span>
  </div>
  <div class="pull-left">
  <h2 class='post-name'> <%= Person.find_by(user_id: @user.id).fullname %></h2>
  <h6><strong> Address: </strong> <%= Person.find_by(user_id: @user.id).address %></h6>
  <h6><strong>Contact Number: </strong><%= Person.find_by(user_id: @user.id).contact_num %></h6>
  <h6> <strong>E-mail Address: </strong><%= Person.find_by(user_id: @user.id).email %></h6>
  </div>
<div class='post-content'>
  <div class="col-md-8">
  <table class="table">
  	<tr><td>
      <strong> Category: </strong> <%= @post.category %> <br>
  		<strong> Weight
      <% if @post.category == 'advertisement' %>
        Offered
      <% else %>
        Needed
      <% end %>
      : </strong> <%= @post.weight %> kgs <br>
  		<strong> Origin: </strong> <%= @post.origin %> <br>
  		<strong> Destination: </strong> <%= @post.destination %>  <br>
  		<strong> Flight Schedule: </strong> <%= @post.date_of_flight.strftime("%b %d, %Y, %I:%M %P") %> <br>
  		<strong> Flight Number: </strong> <%= @post.flight_number %>
  	</td></tr>
  	<tr>
  		<td>
  			 <strong> Details: </strong>
  				<p><%= @post.details %></p>
  		</td>
  	</tr>
  </table>
  </div>


  <br>

  
  <% if @post.is_active %>
    
    <div class="col-md-8">
    <%= render 'bids/list' %>
    </div>
    
    <% if current_user && current_user.id != @post.poster_id %>
    
      <p> 
<!-- <<<<<<< HEAD -->
      <!-- <h2>Add Bid</h2> -->
<!-- ======= -->
      <!-- <h2>Add Bid</h2> -->
      <%= render 'layouts/flash' %>
<!-- >>>>>>> 591bf91b580d5ad7a70ea00082716a700723ecc5 -->
      <%= render 'bids/form' %>
       </p>
       <br>
    <% elsif !current_user%>
        <div class="col-md-8">
          <em><%= link_to "Login", login_users_path %> or 
          <%= link_to "Register",new_user_path %> to proceed with the bidding</em>
        </div>
    <% end %>
  
<% else %>
  <% bid = Bid.find(Transaction.where(post_id: @post.id).first.bid_id) %>
<div class="col-md-8">
<strong>This offer is no longer available</strong>
<p> This offer has been approved to <%= Person.find(bid.bidder_id).fullname %> </p>
</div>
<% end %>
</div>