config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#home'

  resources :users do
    collection do
      get 'login' => 'users#login'
      post 'login' => 'users#sign_in'
      post 'logout' => 'users#logout'
    end
  end

  resources :comments
  resources :posts do
    collection do
      get 'search_results' => 'posts#search_results'
      get 'search_results_destination' => 'posts#search_destination_date'
    end
  end
  resources :transactions
  resources :categories
  resources :bids

  get 'searches/search_username' => 'searches#search_username'
  get 'searches/search_flight_number'=> 'searches#search_flight_number'
  get 'searches/search_destination_date'=> 'searches#search_destination_date'
  get '/my_posts' => 'posts#person_posts'
  get '/my_bids' => 'bids#person_bids'

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  
  def new
    @transaction = Transaction.new 
  end
  
  def index
    @transactions = Transaction.all
  end

  def edit
    @transaction= Transaction.find(params[:id])
  end
  
  def update
    @transaction = Transaction.find(paramas[:id])

    post = Person.find(@transaction.poster)
    if @transaction.save
      post.is_active = false
      post.save
      redirect_to post
    else
      redirect_to post
    end
  end
  


  def show
    @transaction = Transaction.find(params[:id])
  end

  def create
    @transaction = Transaction.new
    @transaction.poster = params[:poster]
    @transaction.bidder = params[:bidder]
    @transaction.post_id = params[:post_id]
    @transaction.bid_id = params[:bid_id]
    @transaction.date = params[:date]
    

    post = Post.find(@transaction.post_id)
    if @transaction.save
      post.is_active = false
      post.save
      redirect_to post
    else
      redirect_to post
    end
  end
  
  private
    def transaction_params
      params.require(:transaction).permit(:poster,:bidder, :post_id, :bid_id, :date )
    end




end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for :transaction, url: transactions_path do |f| %>
  


  <%= hidden_field_tag :post_id, @bid.post_id %>
  <%= hidden_field_tag :bid_id, @bid.id %>
  <%= hidden_field_tag :poster, Post.find(@bid.post_id).poster_id %>
  <%= hidden_field_tag :bidder, @bid.bidder_id %>
  <%= hidden_field_tag :date, Time.now.strftime("%d/%m/%Y %H:%M") %>
  
  <%= button_tag 'Approve', :type=>'submit', :class=>'btn btn-primary'%>
  
  </p>
 
<% end %>
 

app/views/transactions/show.html.erb
<div>
  
  <strong>Poster</strong> <%= Person.find(@transaction.poster).fullname %> <br>
  <strong>Bidder</strong> <%= Person.find(@transaction.bidder).fullname %><br>
  <strong>Date</strong> <%= @transaction.date %> <br>

</div>