config/routes.rb
Rails.application.routes.draw do

   root 'static_pages#home'

  resources :users do
    collection do
      get 'login' => 'users#login'
      post 'login' => 'users#sign_in'
      post 'logout' => 'users#logout'
    end
  end

  resources :comments
  resources :posts do
    collection do
      get 'search_results' => 'posts#search_results'
      get 'search_results_destination' => 'posts#search_destination_date'
    end
  end
  resources :transactions
  resources :categories
  resources :bids

  get 'searches/search_username' => 'searches#search_username'
  get 'searches/search_flight_number'=> 'searches#search_flight_number'
  get 'searches/search_destination_date'=> 'searches#search_destination_date'
  get '/my_posts' => 'posts#person_posts'
  get '/my_bids' => 'bids#person_bids'

end

app/models/bid.rb
class Bid < ActiveRecord::Base

	validates_presence_of :weight
	validates_presence_of :details
	validates_presence_of :flight_number

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base

	validates_presence_of :first_name
	validates_presence_of :last_name
	validates_presence_of :mid_name
	validates_presence_of :address
	validates_presence_of :contact_num
	validates_presence_of :email


	def fullname
		first_name + " " + mid_name + " " + last_name 
	end

end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base

	attr_accessor :password
	before_save :encrypt_password

	validates_presence_of :username
	validates_uniqueness_of :username, :case_sensitive=>false
	validates_presence_of :password
	validates_confirmation_of :password	

	def self.authenticate(username, password)
		user = find_by_username(username)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end	

end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
   
  def new
    @bid = Bid.new 
  end
  
  def index
    @bids = Bid.all
  end

  def edit
    @bid= Bid.find(params[:id])
  end

  def update
    @bid =  Bid.find(params[:id])

    if @bid.update(bid_update_params)
      redirect_to @bid
    else
      render 'edit'
    end
  end

  def show
    @bid = Bid.find(params[:id])
  end

  def create
    @post_id
    @bid = Bid.new(bid_params)
    @bid.bidder_id = current_user.id
    @bid.post_id = params[:post_id]

    if @bid.save 
      redirect_to Post.find(params[:post_id]) 
    else
      flash[:error] = @bid.errors.full_messages.first
      redirect_to post_path(id: params[:post_id])
    end
  end
  
  private
    def bid_params
      params.require(:bid).permit(:post_id,:bidder_id, :weight, :details, :flight_number)
    end

    def bid_update_params
      params.require(:bid).permit(:weight, :details, :flight_number)
    end


 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def new
    @post = Post.new 
  end
  
  def index
    @posts = Post.all
  end

  def edit
    @post= Post.find(params[:id])
    dof = @post.date_of_flight.to_s.split('-')
    @dof_str = dof[1] + "/" + dof[2] + "/" + dof[0]
  end

  def update
    @post =  Post.find(params[:id])

    if @post.update(post_update_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
    @user = User.find(@post.poster_id)
  end

  def create
    @post = Post.new(post_params)
   # @post.poster_id = current_user.id
    @post.date_of_flight = DateTime.strptime(params[:date], '%m/%d/%Y %I:%M %P')
    @post.is_active = true
    if @post.save 
      redirect_to @post
    else
      render 'new'
    end
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = Post.find(params[:id]).destroy
    redirect_to @user
  end

  def search_results
    @flight_number = params[:flight_number]
    @posts = Post.where(flight_number: @flight_number)
  end

  def search_destination_date
    @destination = params[:destination]
    @origin = params[:origin]
    @date = params[:date]
    @posts = Post.where(id: -1)
    post_h = Post.all
    test = 0
    
    if @origin.length > 0 then
      post_h = post_h.where(origin: @origin)
      test += 1
    end

    if @destination.length > 0 then
      post_h = post_h.where(destination: @destination)
      test += 1
    end

    @date_arr = @date.to_s.split('/')

    if @date_arr.length > 0 then
        test += 1
        post_h = post_h.where('extract(year from date_of_flight) = ?', @date_arr[2])
        post_h = post_h.where('extract(month from date_of_flight) = ?', @date_arr[0])
        post_h = post_h.where('extract(day from date_of_flight) = ?', @date_arr[1])
    end

    if test > 0 then
      @posts = post_h
    end
  end
  
  
  private
    def post_params
      params.require(:post).permit(:poster_id, :weight, :date_of_flight, :details, :category, :flight_number, :is_active, :origin, :destination )

    end

    def post_update_params
      params.require(:post).permit(:poster_id, :weight, :date_of_flight, :details, :category, :flight_number, :is_active, :origin, :destination )
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def show
		@user = User.find(params[:id])

		if @user
			@person = Person.find_by(user_id: @user.id)
			@posts = Post.where(poster_id: @user.id)
			@comments = Comment.where(user_id: @user.id)
		else
			redirect_to :root
		end
	end

	def new
		
	end

	def create
		@user = User.new(user_params)

		if @user.save
			@person = Person.new(person_params)
			if @person.save
				flash[:notice] = "Successfully Created Account!"
				redirect_to login_users_path
			else
				flash.now[:error] = @person.errors.full_messages.first
				render 'users/new'
			end
		else
			flash.now[:error] = @user.errors.full_messages.first
			render 'users/new'
		end
	end

	def edit
			
	end

	def update
			
	end
 
  def destroy
    
    @User = User.find(current_user.id)

    @posts = Post.where(user_id: current_user.id)

    @posts.each do |x|
      x.destroy
    end

  end
  def login
    
    if current_user == nil
      @user = User.new
    end

  end

  def sign_in
    
    username = params[:user][:username]
    password = params[:user][:password]

    user = User.authenticate(username, password)

    if user
      session[:user_id] = user.id
      @user = (current_user.role == 'admin')? User.find(current_user.id) : nil
      redirect_to :root
    else
      flash[:error] = "Invalid username or password."
      redirect_to login_users_path
    end
  end

	def logout
		session[:user_id] = nil
		redirect_to :root		
	end

	private
		def user_params
			params.require(:user).permit(:username, :password, :password_confirmation, :role)
		end

		def person_params
			params.require(:person).permit(:first_name, :last_name, :mid_name, :address, :contact_num, :email).merge(:user_id => @user.id)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div id="flash-container">
	<% flash.each do |name, msg| %>
		<%= content_tag :div, msg, :class => "flash #{name}" %>
	<% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default color-change navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to :root, class:'pull-right' do %>
      <%= image_tag('Logo3-white.png', :class => "img", :alt => "Brand") %>
      <% end %>
    </div>
     

    <!-- Collect the nav links, forms, and other content for toggling -->
    
      <ul class="nav navbar-nav navbar-left">
        <li><%= link_to 'Home', root_path %></li>
        
         <% if current_user %>
            <li><%= link_to 'Profile',  user_path(current_user.id) %></li>
            <li><%= link_to 'Add Post', new_post_path %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Bids<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'My Bids', my_bids_path %></li>
          </ul>
          </li>
          
        </li>

      </ul>

     <%= form_tag({controller: 'searches', action: 'search_username'}, method: "get", class: 'navbar-form navbar-left') do %>
        <%= text_field_tag :username, nil, placeholder: 'Username', class: 'form-control' %>

        <button type ="submit" class="btn btn-default color-blue"><span class="glyphicon glyphicon-search"></span></button>

    <% end %>  
    
    

     <%else%>
        <li><%= link_to 'Register',  new_user_path %></li>
     <% end %> 
     
      </ul>
   <!-- /.navbar-collapse -->
    <ul class="nav navbar-nav navbar-right">
        <li><% if current_user %>
        <p class="navbar-text color-change">Logged in as <strong><%= current_user.username %></strong></p>
    	  <% end %></li>
    	  <div class="navbar-right">
        <% if current_user %>
      		<!--<button type="submit" class="btn btn-default">Logout</button>-->
        <%= button_to 'Logout', logout_users_path, method: :post, class: "btn btn-default navbar-btn outline navbar-right", type: "button"%>
        <% else %>
          <!--<button type="submit" class="btn btn-default">Login</button>-->
        <%= button_to 'Login', login_users_path, method: :get, class: "btn btn-default navbar-btn outline navbar-right", type: "button"%>
        <% end %>
        </div>
        </li>
      </ul>
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_search.html.erb
<div class="container-fluid">


  <%= form_tag({controller: 'searches', action: 'search_flight_number'}, method: 'get') do %>
      <div class="form-group">
      <%= label_tag :flight_number %><br>
      <%= text_field_tag :flight_number, nil, placeholder: 'Flight number', class: 'form-control' %>
      </div>
      <button type ="submit" class="btn btn-default pull-right">Search</button>
  <% end %> 

</div>
<div class="container-fluid">
  <%= form_tag({controller: 'searches', action: 'search_destination_date'}, method: 'get') do %>
  <div class="form-group">
      <%= label_tag :destination %><br>
      <%= text_field_tag :destination, nil, placeholder: 'Destination', class: 'form-control' %>
  </div>
  <div class="form-group">
      <%= label_tag :origin %><br>
      <%= text_field_tag :origin, nil, placeholder: 'Origin', class: 'form-control' %> 
  </div>
  
  <div class="form-group">
    <label for="exampleInputEmail1">Date</label>
    <%= text_field_tag :date, nil, :data => {:provide => "datepicker"}, class: 'form-control' %>
  </div>

  <button type="submit" class="btn btn-default pull-right">Search</button>
<% end %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $('.datepicker').datepicker();
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flightweight</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'flavicon.png' %>
</head>
<body>

<%= render 'layouts/header' %>

<div id="wrapper">
    
    <div id="sidebar-wrapper">
        <%= render 'layouts/search' %>
    </div>
    <div id="page-content-wrapper">
        <div class="page-content">
            <!-- <div class="container"> -->
                <!-- <div class="row"> -->
                    <div class="col-md-12">
                        <div id="content">
                        <%= yield %>
                        </div>
                    </div>
                <!-- </div> -->
            <!-- </div> -->
        </div>

        <footer class="foot-er"><div><%= image_tag('Footer3.png', :class => "img-foot") %></div></footer>

        <!-- <div id="footer" class="footer"><div class="row spread"><%#= image_tag('Footer3.png', :class => "img-foot") %></div></div> -->

      </div>
    </div>
</div>

</body>
</html>